percona/mongodb_exporter

collector/mongod/oplog_status.go

Fixes for Issue #9 :
1. Retry queries for oplog timestamps once.
2. Perform 2 x .find().sort().limit() queries instead of one big aggregate. This should help reduce the impact of the querying.
Tested and things are looking good so far.
Tim

Oplog error fixes

---

README.md
mongodb_exporter.go

* With MONGODB_URI you can specify MongoDB uri which is more secure than -mongodb.uri flag.
* With HTTP_AUTH you can enable http basic auth. -auth.user, -auth.pass flags were removed as insecure.

Added support for MONGODB_URI and HTTP_AUTH env vars.

---

Dockerfile
README.md
collector/mongodb_collector.go
collector/mongodb_collector_test.go
mongodb_exporter.go
vendor/vendor.json

Moving+renaming repo to Percona from Percona-Labs

---

collector/mongodb_collector.go

The only change is line 67, the rest is whitespace/lint fixes from my go IDE.
This fixes a problem that only happens on 3.2.10-3.2.12 with SCCC config servers by setting mongos connections to use Primary-only read preference (mgo.Strong).
MongoDB issue: https://jira.mongodb.org/browse/SERVER-27864

Use Primary readpreference (mgo.Strong) when using mongos to prevent SERVER-27864

---

collector/mongod/metrics.go

https://docs.mongodb.com/manual/reference/command/serverStatus/#serverstatus.metrics.repl
Adds counts of replication execution counters, queue sizes, etc. This appears in 3.0+ only, but the code is setup to ignore these metrics if the server is too old (due to bson 'omitempty' hints and if != nil checks).
Added stats:
```
$ curl -sk http://localhost:9104/metrics|grep ^mongodb|grep repl|grep exec
mongodb_mongod_metrics_repl_executor_event_waiters 0
mongodb_mongod_metrics_repl_executor_queue{type="dbWorkInProgress"} 0
mongodb_mongod_metrics_repl_executor_queue{type="exclusiveInProgress"} 0
mongodb_mongod_metrics_repl_executor_queue{type="free"} 5
mongodb_mongod_metrics_repl_executor_queue{type="networkInProgress"} 0
mongodb_mongod_metrics_repl_executor_queue{type="ready"} 0 …
```

Add db.serverStatus().metrics.repl.executor stats

---

collector/mongodb_collector.go
mongodb_exporter.go
shared/connection.go
shared/utils.go

Based on https://github.com/dcu/mongodb_exporter/pull/18
Fix #18

Enable tls connection with mongo server

---

Gopkg.lock
vendor/github.com/stretchr/testify/require/doc.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/requirements.go

I wanted to `make` this project but was unable to due to a missing dependency. I ran a `dep ensure` and it now `make`'s it without problems.
I couldn't open an issue so I'll ask for it here. I see that you are using the `.promu.yml` file to be able to crossbuild releases which is great. What I'm missing though is these built binaries being put in the actual releases, which would make this project that much more helpful for installing on a server.
For example, I use SaltStack as a configuration management tool and would rather download a binary then to have to install all the dependencies and then build it myself. This is error prone and time-consuming which is unnecessary since you've got the tools already set up to release these binaries.
Would you accept a pull request which would …

Add required testify dependency

---

collector/mongod/metrics.go

The metrics were previously added but they were never set. This PR sets the metrics for the TTL stats.

PMM-3401: Added collection of TTL metrics

---

collector/mongod/index_usage.go

The index stats lacked db as a label. I.e. a "foo" collection's stats from databases "x" and "y" would have been indistinct, or one overwriting the other. This fixes that.

Fix for broken labels on index_usage metrics

---

README.md

This PR add the helm chart link to the readme.

Add helm chart to readme

---

.travis.yml
Makefile

https://travis-ci.com/percona/mongodb_exporter/jobs/210662508#L393
Here are results with `--kill-after` flag.

PMM-4236 Improve coverage speed.

---

CHANGELOG.md
shared/connection.go

This is very useful when you can see connections from mongo-export in logs.

add appName to connection

---

CHANGELOG.md
collector/mongodb_collector.go
mongodb_exporter.go
shared/connection.go
testdata/mongodb_exporter.testFlagHelp.golden

Some of the CLI flags have been removed due to official MongoDB driver usage.
With this driver, it is possible to provide all those parameters with MongoDB URI connection string.

PMM-4719: Remove redundant flags and parameters.

---

exporter/diagnostic_data_collector.go
exporter/exporter.go
exporter/replset_status_collector.go
main.go

- Added error logs instead of stop collecting metrics in case of errors.
- Added options to disable getDiagnosticData and replicasetGetStatus collectors

PMM-6608 Added more logs

---

exporter/diagnostic_data_collector.go
exporter/diagnostic_data_collector_test.go
exporter/exporter.go
exporter/general_collector.go
exporter/general_collector_test.go
exporter/v1_compatibility.go
internal/tu/testutils.go

New PR to replace https://github.com/percona/mongodb_exporter/pull/207
This is based on PMM-6610

PMM-6585 Always expose mongodb_up metric

---

exporter/secondary_lag_test.go
exporter/v1_compatibility.go
internal/tu/testutils.go

Feature Build: https://github.com/Percona-Lab/pmm-submodules/pull/1145

PMM-4547 Replicaset lag incorrect

---

.github/workflows/go.yml
main.go
main_test.go

Fixed indexstats parameter and created a new buildExporter func to make the main func simpler.
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1522

PMM-7470 Fixed indexstats params

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md

change in the contribution guide, mention reviewers and adding PR
template.

changing contribution guide according to the new standard

---

README.md

Actualize flags table in README

---

README.md
exporter/collstats_collector.go
exporter/exporter.go
exporter/indexstats_collector.go
main.go

Implemented autodiscover collections because sometimes you don't want to set all collections and more convenient to set only databases

Add discovering-mode

---

README.md

Update flags
Ref.: https://github.com/percona/mongodb_exporter/pull/249#issuecomment-814829306

Update README with direct-connect

---

collector/mongos/sharding_changelog.go

panic when GetShardingChangelogStatus

panic when GetShardingChangelogStatus

---

collector/mongos/sharding_changelog.go

Hello. I've  fixed issue [PMM-1238](https://jira.percona.com/browse/PMM-1238). Could you review it, please.

PMM-1238 fix mongos sharding changelog metric

---

main.go

WIP Draft PR to create a testing feature build

PMM-7941 Test for QA. direct-connect tru by default

---

README.md

Udpate Readme with discord link

---

.github/workflows/go.yml

[PMM-7902](https://jira.percona.com/browse/PMM-7902) (optional, if ticket reported)
---

PMM-7902 Remove Go 1.15

---

CHANGELOG
exporter/topology_info.go

[PMM-8489](https://jira.percona.com/browse/PMM-8489) (optional, if ticket reported)
---

PMM-8489 fix: topology in mongos

---

collector/mongod/replset_conf.go

[PMM-6113](https://jira.percona.com/browse/PMM-6113) (optional, if ticket reported)
---

fix(PMM-6113): apply patch found in ticket

---

CHANGELOG
exporter/dbstats_collector.go
exporter/dbstats_collector_test.go
exporter/utils_test.go
exporter/v1_compatibility.go

Provide old mongod metrics for dbstats

---

README.md

Improve docs on the previous version of the Percona MongoDB exporter
---

README.md: Improve notes on the previous versions of the exporter

---

exporter/common.go
exporter/common_test.go

Fixed the filter issue found in PMM-9312 tests

PMM-9312 Fix MongoFilter

---

exporter/diagnostic_data_collector.go
exporter/exporter.go
exporter/exporter_test.go
main.go

[PMM-9471](https://jira.percona.com/browse/PMM-9471) (optional, if ticket reported)
Build: https://github.com/Percona-Lab/pmm-submodules/pull/2297
---

PMM-9471 Context deadline

---

go.mod
main.go

[PMM-9507](https://jira.percona.com/browse/PMM-9507) (optional, if ticket reported)
---

PMM-9507 Better help.

---

exporter/diagnostic_data_collector.go
exporter/exporter.go
exporter/exporter_test.go
main.go

[PMM-9458](https://jira.percona.com/browse/PMM-9458) (optional, if ticket reported)
[PMM-9471](https://jira.percona.com/browse/PMM-9471) (optional, if ticket reported)
---

PMM-9458-9471 Disable collectors on limit and context deadline

---

CHANGELOG

Updated CHANGELOG for v0.31.0 release.

Updated CHANGELOG

---

exporter/base_collector.go
exporter/collstats_collector.go
exporter/dbstats_collector.go
exporter/diagnostic_data_collector.go
exporter/diagnostic_data_collector_test.go
exporter/exporter.go
exporter/general_collector.go
exporter/indexstats_collector.go
exporter/replset_status_collector.go
exporter/serverstatus_collector.go
exporter/top_collector.go
exporter/topology_info.go
exporter/topology_info_test.go

Changes from 2.27.0

---

README.md
REFERENCE.md

[PMM-1458](https://jira.percona.com/browse/PMM-1458) : Update documentation for MongoDB exporter
Resolves #477

PMM-1458 Create reference document

---

exporter/dsn_fix/dsn_fix.go
exporter/dsn_fix/dsn_fix_test.go
exporter/exporter.go

[PMM-9320](https://jira.percona.com/browse/PMM-9320)
- https://github.com/percona/pmm-agent/pull/372
FB:
- https://github.com/Percona-Lab/pmm-submodules/pull/2494

PMM-9320: fix auth creds

---

exporter/dsn_fix/dsn_fix.go
exporter/exporter_test.go

[PMM-10265](https://jira.percona.com/browse/PMM-10265)

PMM-10265: fallback to original DSN if it is non-URI

---

exporter/diagnostic_data_collector.go
exporter/diagnostic_data_collector_test.go
exporter/exporter.go
exporter/serverstatus_collector.go
exporter/top_collector.go
exporter/topology_info.go
exporter/topology_info_test.go
exporter/v1_compatibility.go
exporter/v1_compatibility_test.go

[PMM-9968](https://jira.percona.com/browse/PMM-9968)
Build: SUBMODULES-2595

PMM-9968 use logger with level

---

exporter/diagnostic_data_collector_test.go
exporter/v1_compatibility.go

[PMM-10631](https://jira.percona.com/browse/PMM-10631) (optional, if ticket reported)
FB: https://github.com/Percona-Lab/pmm-submodules/pull/2748
---

PMM-10631: Add label to mongodb_version_info metric with Edition info

---

exporter/v1_compatibility.go

metric mongodb_mongos_sharding_balancer_enabled fixed.
---
- [ X] Tests passed.

function balancerEnabled fixed

---

exporter/dsn_fix/dsn_fix.go
exporter/dsn_fix/dsn_fix_test.go
go.mod
go.sum

[PMM-11844](https://jira.percona.com/browse/PMM-11844)
- https://github.com/percona/pmm/pull/1903
FB: 
- https://github.com/Percona-Lab/pmm-submodules/pull/3158

PMM-11844: fix setting auth props

---

.github/workflows/go.yml
.github/workflows/release.yml

[PMM-12339](https://jira.percona.com/browse/PMM-12339)

PMM-12339 remove go tip

---

exporter/currentop_collector.go

PMM-7 Use pkg/errors

---

.github/workflows/go.yml
Makefile
exporter/currentop_collector_test.go
exporter/v1_compatibility.go

PMM-7 fix tests and a small improvement.

---

README.md
REFERENCE.md

[PMM-12712](https://jira.percona.com/browse/PMM-12712)
[PMM-12712]: https://perconadev.atlassian.net/browse/PMM-12712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PMM-12712 Doc about new shards collector.

---

exporter/v1_compatibility.go

[PMM-12350](https://jira.percona.com/browse/PMM-12350) (optional, if ticket reported)
--- …

PMM-12350 Fix mongos errors.

---

exporter/exporter.go
exporter/topology_info.go
exporter/topology_info_test.go
exporter/v1_compatibility.go
exporter/v1_compatibility_test.go
internal/proto/proto.go

[PMM-12350](https://jira.percona.com/browse/PMM-12350) (optional, if ticket reported)
--- …

PMM-12350 Fix node type detection.

---

exporter/feature_compatibility_version_collector.go

fix panic in v0.41.0.

---

.github/workflows/release.yml
.goreleaser.yml
Makefile

PMM-7 update goreleaser version and config

---

go.mod
go.sum

[PMM-13426](https://jira.percona.com/browse/PMM-13426) 
---
[PMM-13426]: …

PMM-13426: update PBM sdk

---

.github/workflows/scorecard.yml
README.md

PMM-7 integrate scorecard.

---

README.md

[PMM-7](https://jira.percona.com/browse/PMM-7) 
---
[PMM-7]: …

Add forum badge

---

.goreleaser.yml

Fix for the failing CI at: https://github.com/percona/mongodb_exporter/actions/runs/15390734125/job/43299370983

PMM-7specify build IDs for multiple binaries
