- Dockerfile
- LICENSE
- README.md
- mongodb_exporter.go
This is so the mysql and mongo exporters run on the same port by default. It can be changed in the configuration but  this simplifies things in other systems.
> Change port from 9001 to 9104 by default

- Makefile.COMMON
- mongodb_exporter.go
Adding -version flag to mongodb_exporter.go, and flags to 'go build' step to compile the version into the binary.
Result:
`[tim@centos7 prometheus_mongodb_exporter]$ ./mongodb_exporter -version
mongodb_exporter version: 0.1.0
git commit hash: e0afdfe1af1b979fa3472e3eca38d776b27af2ce`
> Adding -version flag to mongodb_exporter.go

- collector/mongod/rocksdb.go
- collector/mongod/server_status.go
This adds all available metrics from RocksDB to the exporter with a majority of the code being string-parsing code. *RocksDB's 'uptime' was excluded because it's == to the uptime of mongod.
```
$ curl -s http://localhost:37017/metrics|grep ^mongodb_mongod_rocks
mongodb_mongod_rocksdb_background_errors 0
mongodb_mongod_rocksdb_block_cache_bytes 7.90626304e+08
mongodb_mongod_rocksdb_compaction_avg_seconds{level="L0"} 0.477
mongodb_mongod_rocksdb_compaction_avg_seconds{level="L5"} 3.014
mongodb_mongod_rocksdb_compaction_avg_seconds{level="L6"} 7.228
mongodb_mongod_rocksdb_compaction_avg_seconds{level="Sum"} 2.68
mongodb_mongod_rocksdb_compaction_bytes_per_second{level="L0",type="write"} 1.291845632e+08
mongodb_mongod_rocksdb_compaction_bytes_per_second{level="L5",type="read"} 7.47634688e+07 …
```
> Adding rocksdb support to exporter

- collector/mongod/rocksdb.go
Unit-parsing fixes for numbers ending in M, B, T (million, billion, trillion). The original code only had support for K=1000 from the output and broke when the numbers became billion+.
> RocksDB unit string-parse fix for B, M and T (billion, million and trillion) strings->numbers

- collector/mongod/server_status.go
Process inMemory stats using the already-existing WiredTiger structs that match.
At a later time I'd like to rename the metric names to suggest the metric is for in-memory wiredtiger or not, but this was a very low-effort starting point.
> Process inMemory stats as WiredTiger

- collector/mongod/rocksdb.go
To fix #24, this moves to using the optional RocksDB 'counters' Igor Canadi from mongorocks recommended, enabled by the flag '--rocksdbCounters 1' or in the mongod.conf.
Moving to the 'counters' caused some new metrics to be available (mostly read latency and block cache hit/miss). Some metrics not available in 'counters' (but were in the human-readable output) are requested for addition in https://github.com/mongodb-partners/mongo-rocks/issues/34.
A PR in the https://github.com/Percona-Lab/grafana_mongodb_dashboards project is upcoming for this change.
> Use Rocksdb Counters to fix #24

- collector/mongod/replset_status.go
1. Reset metric vectors before setting them to clear stale replset states (ie: only display current replication state). PR #17 partially duplicates this change.
2. Add new metric: 'mongodb_mongod_replset_my_name' to show the 'name' of the replica set member. This will be used to join on the member_optime_date metric to select a more accurate metric for lag.
Example output post-change:
```
$ curl -s http://localhost:9104/metrics|grep replset_my_name
mongodb_mongod_replset_my_name{name="localhost:27017",set="test1"} 1
```
> Fixes to improve replication lag accuracy

- mongodb_exporter.go
- vendor/vendor.json
* Added `-web.auth-file` flag to alternatively support setting up http basic auth using config file. In our case, for PMM.
* Added HTTPS/TLS support.
> Added http basic auth and https/tls support.

- README.md
The README tells you to set MONGO_URI and this doesn't work. The code is looking for MONGO_URL, updated README to remove confusion.
> (fix) typo in the README MONGO_URI should be MONGO_URL

- collector/mongod/wiredtiger.go
As recommended by @denis-protyvenskyi for troubleshooting WT cache problems, I've added two more cache metrics to the exporter from WT's stats:
1. "tracked bytes belonging to internal pages in the cache"
2. "tracked bytes belonging to leaf pages in the cache"
The addition of these fields does not break the Grafana/PMM dashboard projects as each key from the vector I appended to is explicitly selected in our queries.
Note: my Golang IDE does auto whitespace fixing + Golint'ing, so that is why it looks like a lot has changed, but really the only changes are on lines 212-213 - adding two new keys to the metric vector.
> Export WiredTiger Cache leaf page and internal page tracked bytes

- collector/mongod/replset_status.go
Adding the replSetGetStatus.date field to the exporter. This is needed so we know what time the status was gathered.
> Compare this to the value of the lastHeartbeat to find the operational lag between the current host and the other hosts in the set.
```
replSetGetStatus.date
value of the date field is an ISODate of the current time, according to the current server. Compare this to the value of the lastHeartbeat to find the operational lag between the current host and the other hosts in the set.
```
Link: https://docs.mongodb.com/manual/reference/command/replSetGetStatus/#replSetGetStatus.date
> Add 'date' field from replSetGetStatus for lag calculations

- collector/mongodb_collector.go
- shared/connection.go
When mongodb_exporter cannot connect to the database after starting, it crashes.
In collector/mongodb_collector.go we ask for a session and immediately call a 'defer session.Close()' on it. When the exporter cannot connect to the DB this means we call a .Close() on a nil, then the exporter crashes.
This fix moves the 'defer session.Close()' to be within the if-nil brackets so this never happens. This will resolve crashes a few users have reported. This will fix issue #50.
Also, redaction of username+passwords from log messages is fixed in this PR as I noticed that problem at the same time when a user reported logs of this crash with usernames+passwords in the errors.
Lastly, connect timeout to the database was reduced to 5 seconds to stop piling up connections. Prometheus queries the …
> Move mgo.Session deferred-Close() to after the if-nil check, redact username+password from log messages, reduce connect timeout

- collector/mongod/server_status.go
- collector/mongod/storage_engine.go
Our 'mongodb_mongod_storage_engine' metric seems to break on MongoDB 2.x because the db.serverStatus().storageEngine document did not exist in this version.
This changes the exporter to return 'mmapv1' as the storage engine type if db.serverStatus().storageEngine (3.0+ only) does not exist and/but db.serverStatus().backgroundFlushing does exist (only shows on MMAPv1 instances). The 2nd condition is to avoid TokuMX showing as MMAPv1, mostly.
EDIT: My golang IDE fixed some whitespace alignment on 2 x structs, no logic changed to those lines.
> Return 'mmapv1' as storage engine if db.serverStatus().storageEngine doesn't exist (added in 3.0)

- collector/mongod/oplog_status.go
- shared/utils.go
1. Added query comments to .Find() queries in oplog_status.go (only .Find() queries).
2. Cleaned up (terrible) duplicated logic/code for getting oplog timestamps that I made in oplog_status.go long ago.
3. Added a function to shared/utils.go to add code comments (File+LineNum) to MongoDB queries.
Query comment output example in Profiler:
```
test1:PRIMARY> db.system.profile.find({op:"query",ns:{$ne:"local.system.profile"}},{op:1,ns:1,query:1,command:1}).pretty()
{
"op" : "query",
"ns" : "local.oplog.rs",
"query" : {
"find" : "oplog.rs",
"sort" : {
"$natural" : -1
},
"skip" : 0,
"limit" : 1,
"batchSize" : 1,
"singleBatch" : true,
"comment" : "/home/tim/go/src/github.com/percona/mongodb_exporter/collector/mongod/oplog_status.go:90"
}
}
{
"op" : "query",
"ns" : "local.oplog.rs",
"query" : { …
```
> Add MongoDB Query-comments to .Find() operations

- README.md
I was concerned that I needed to rewrite the authentication code for mongodb_exporter - but the mechanism can be provided by URI. This documents this for future users.
> Document MONGODB-X509 auth

- .gitignore
- CONTRIBUTING.md
- collector/mongodb_collector_test.go
Use connection string from `TEST_MONGODB_URL` envvar which defaults to `localhost:27017` still.
This makes testing against my local minikube-deployed mongodb easier. Using the `TEST_` prefix from past experience of people running tests against dbs where they actually cared about the data in by mistake when using just `MONGODB_URL`.
Also drive-by ignore my editor's temp files.
>  Support integration tests against non-locahost db

- collector/mongod/server_status.go
- collector/mongod/server_status_test.go
Expose as a gauge with the version as a label and a value of 1.
Follows this scheme for doing software versions:
https://www.robustperception.io/exposing-the-software-version-to-prometheus/
Will conflict with https://github.com/percona/mongodb_exporter/pull/86 but I can resolve that.
> Export mongodb version as a metric

- Makefile
2 portability issues in Makefile:
1. Race detector is only supported on amd64, so '-race' cannot be
used other architectures
2. 'uname -m' reportes 'aarch64' on arm64 CPUs, but the corresponding
value accepts in GOARCH is 'arm64'.
> ARM64-specific fixes.

- collector/mongodb_collector.go
Fixes URI logging in plain text including credentials when no session can be created.
> Redact Mongo URI

- .gitignore
- collector/mongodb_collector.go
- mongodb_exporter.go
- shared/connection.go
Adds the following flags:
* -mongodb.socket-timeout
* -mongodb.sync-timeout
I left the defaults as they were, but I think it might be a good idea to change them as well. The MongoDB driver has a default for the sync timeout of 7 seconds ([session.go#L1706](https://github.com/percona/mongodb_exporter/blob/develop/vendor/gopkg.in/mgo.v2/session.go#L1706)) and a default value for the socket timeout of one minute ([session.go#L1716](https://github.com/percona/mongodb_exporter/blob/develop/vendor/gopkg.in/mgo.v2/session.go#L1716)) whereas the exporter uses a much longer default for the sync timeout of one minute and an extremely short default of 3 seconds for the socket timeout.
We've found that the default socket timeout is way too short when you have a recovering replica. It may take quite a …
> PMM-2530: Add timeout flags

- collector/mongos/sharding_status.go
After checking the code I figure out that the values for **balancerIsEnabled** and **balancerChunksBalanced** were exchanged
> PMM-2620: Fix balancerIsEnabled & balancerChunksBalanced values

- .promu.yml
It seems that none of the releases since v0.3.1 include binaries. I'm not sure if this is intentional, but this exporter is much easier to use if I can simply download a precompiled binary directly from GitHub rather than compiling and packaging the exporter myself.
NOTE: I have no idea if the changes made in this pull request will actually fix this issue. I inspect the code changes between v0.3.1 and v0.3.2 and can't see anything obvious which would have resulted in binaries no longer being published. Although, I'm not sure what the release process for this exporter even looks like so it's possible that the maintainers are publishing new versions locally rather than using [Travis](https://docs.travis-ci.com/user/deployment/releases/) and that the omission of binaries was a simple …
> Build binaries

- collector/mongod/wiredtiger.go
A small typo seems to have happened. Read tickets out were labelled as write, and vice versa. This reverses that.
> A fix of labels for wiredtiger_concurrent_transactions_out_tickets

- collector/mongod/collections_status.go
If a collection is removed the metrics value for that collection will still be exposed until the exporter get restarted since the gauge is not reset.
> Reset the gauge for collections metrics.

- CONTRIBUTING.md
- README.md
- collector/mongodb_collector_test.go
- mongodb_exporter.go
Be consistent in  usage of env var MONGODB_URI.   Currently, documentation say "MONGODB_URL", but code is looking for MONGODB_URI.
> PMM-3106: Be consistent and use MONGODB_URI everywhere.

- collector/mongodb_collector_test.go
From this moment we can see which metrics wasn't described and/or collected when test fails.
> PMM-3524: Add information about missing metrics in test.

- collector/mongod/collections_status.go
- collector/mongod/rocksdb.go
- collector/mongos/collections_status.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- collector/mongodb_collector.go
- mongodb_exporter.go
- shared/connection.go
- testdata/mongodb_exporter.testFlagHelp.golden
I would like to be able to reproduce behaviour similar to mongo client flag : `--authenticationDatabase`
Associated mongo client documentation : https://docs.mongodb.com/manual/reference/program/mongo/#cmdoption-mongo-authenticationdatabase
If not setting, default will be an empty string  and behaviour will be similar to the actual. Mongo will use the same database that defined in the connection string.
> Add Authentification Database option when connect to mongo

- collector/common/op_counters.go
- collector/common/server_status.go
- collector/mongod/server_status.go
Hi! When metrics were split on common and mongo(d\s), metric "mongodb_op_counters_total" from ServerStatus was lost on mongos.
> return missing metrics from mongos

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- collector/mongos/sharding_status.go
- go.mod
- go.sum
- shared/utils.go
- vendor/github.com/Masterminds/semver/LICENSE.txt
- vendor/github.com/Masterminds/semver/collection.go
- vendor/github.com/Masterminds/semver/constraints.go
- vendor/github.com/Masterminds/semver/doc.go
- vendor/github.com/Masterminds/semver/fuzz.go
- vendor/github.com/Masterminds/semver/version.go
Those metrics have removed due to design changes in MongoDB 3.6+. Starting in version 3.6, the balancer no longer takes a “lock” so those metrics have no sense. For more information see: "https://docs.mongodb.com/v3.6/reference/config-database/#config.locks". For previous versions of MongoDB, those metrics will be working as before.
> PMM-2717 Removed metrics "mongodb_mongos_sharding_balancer_lock_*"

- Makefile
As we pack it without `.git` directory, variables will be empty and throw a following warning while building with PMM-submodules:
```
+ make build
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
```
The `COMPONENT_{VERSION|BRANCH}` will be added to `build/bin/build-client-binary` of the PMM-submodules
> PMM-6377: Rework variables

- .github/workflows/go.yml
- main.go
- main_test.go
This branch is to keep the main as the real main branch with the latest changes.
> Merge release 0.20.2 into main

- .goreleaser.yml
In order to align release tarbals with other community prom exporter releases it may be good to have the folder inside tar.gz archive like for example here:
https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
We need this to deploy all exporters with single Ansible role https://github.com/entercloudsuite/ansible-prometheus-exporter
Current archive dirrectory structure breaks this flow.
> Add directory into releases archives

- README.md
Removed `Build the exporter` content that is repeated twice in the README file
When all checks have passed and the code is ready for review, please add `pmm-review-exporters` as the reviewer. That would assign people from the review team automatically.
> Removed repeated `Build the exporter`

- exporter/exporter.go
- exporter/exporter_test.go
- main.go
This is a fix for https://jira.percona.com/browse/PMM-7128
Ref.: https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo/options#ClientOptions.SetDirect
TODO: When all checks have passed and code is ready for the review, please add `pmm-review-exporters` as the reviewer. That would assign people from the review team automatically.
> Fix issue with DirectConnect

- .github/pull_request_template.md
- .github/workflows/ready-for-review.yml
Add gh action that would assign review team for the PR that are ready.
Clean PR template.
When all checks have passed and code is ready for the review, please add `pmm-review-exporters` as the reviewer. That would assign people from the review team automatically.
> Adding auto assign review team

- collector/mongod/replset_conf.go
Faced with similar problem described in [PMM-6113](https://jira.percona.com/browse/PMM-6113)
I applied part of patch offered by author of the ticket and it helped me to fix error `Failed to get replSetGetConfig: IntDecodeValue can only truncate float64 to an integer type when truncation is enabled`.
> PMM-6113 fix replSetGetConfig parse error

- README.md
The current chart link was deprecated and moved to https://github.com/helm/charts/tree/master/stable/prometheus-mongodb-exporter
> Update helm chart link

- exporter/metrics.go
Add common labels to members info parsed from `replSetGetStatus()`. Also, add `member_state` as a label if exists. Without these changes, members metrics almost useless because we have only `member_idx` label. So, for example, calculate replication lag as the difference between `optimeDate` fields isn't possible because we don't know who is primary and to which cluster this member belongs to.
> More labels for replSetGetStatus() info

- .gitignore
- exporter/secondary_lag_test.go
- exporter/v1_compatibility.go
- go.mod
- go.sum
[PMM-6864](https://jira.percona.com/browse/PMM-6864)
I tried to fill every metric needed for https://pmmdemo.percona.com/graph/d/mongodb-replicaset-summary/mongodb-replset-summary?orgId=1&refresh=1m
But this one is still missing: `mongodb_tcmalloc_cache_bytes`
---
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1720
> PMM-6864 missing old metrics

- exporter/collstats_collector.go
- go.mod
- go.sum
Includes additional information about collection stats about "storage".
```
mongodb_mydb_mycol_storageStats_avgObjSize{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 238
mongodb_mydb_mycol_storageStats_capped{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 0
mongodb_mydb_mycol_storageStats_count{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 57
mongodb_mydb_mycol_storageStats_freeStorageSize{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 0
mongodb_mydb_mycol_storageStats_indexSizes_id{cl_id="5f107dfb3a6fc97a81753480 …
```
> Add storage stats to collection metrics

- README.md
In the README
> The build process uses the dockerized version of goreleaser so you don't need to install Go.
Just run `make build` and the new binaries will be generated under the build directory.
, but it must be `make release`.
---
> README - Replace `make build` with `make release`

- go.mod
- go.sum
from https://github.com/percona/mongodb_exporter/pull/295#issuecomment-922467133
This will fix Apple silicon mac imcompatibility issue of go test.
<a href="https://gyazo.com/fe66e500cd8c6a9efc1da1f1268013b5"><img src="https://i.gyazo.com/fe66e500cd8c6a9efc1da1f1268013b5.png" alt="Image from Gyazo" width="876"/></a>
---
> Upgrade gopsutil for Apple silicon mac compatibility of go test

- exporter/v1_compatibility.go
- go.mod
github.com/prometheus/common/log was removed in favor of Prometheus internally using github.com/go-kit/kit/log (and later github.com/go-kit/log). This exporter still uses the removed package, which prevents downstream importers from being able to upgrade the prometheus/common module.
This PR removes the only reference to that package and replaces it with a call to the existing logrus logger.
Signed-off-by: Robert Fratto <robertfratto@gmail.com>
> Remove dependency on github.com/prometheus/common/log

- exporter/exporter.go
- exporter/exporter_test.go
The Grafana Agent (https://github.com/grafana/agent) embeds mongodb_exporter as an integration, where it needs to be able to call into the exporter's HTTP handler for its all-in-one server. This endpoint also needs to only return metrics for the exporter itself and not from the global registry, which is populated by unrelated metrics.
Signed-off-by: Robert Fratto <robertfratto@gmail.com>
> Expose exporter.Handler and allow disabling default registry

- .goreleaser.yml
- .scripts/default/mongodb_exporter.example
- .scripts/postinst
- .scripts/systemd/mongodb_exporter.service
[PMM-5598](https://jira.percona.com/browse/PMM-5598)
Add building deb and rpm packages.
---
> Add build deb and rpm packages.

- .github/check-license.go
- .github/workflows/go.yml
- exporter/common.go
- exporter/common_test.go
- exporter/debug.go
- exporter/debug_test.go
- exporter/secondary_lag_test.go
- exporter/utils_test.go
- exporter/v1_compatibility.go
- exporter/v1_compatibility_test.go
- internal/tu/docker_inspect.go
- internal/tu/docker_inspect_test.go
- main_test.go
- tools/tools.go
[PMM-5471 Add license checks to mongodb_exporter](https://jira.percona.com/browse/PMM-5471)
Adds the license header text to all existing go files without one, and include the license checker in CI.
> PMM-5471 add license checks

- exporter/collstats_collector.go
`$collStats` is invoked by exporter to get collection statistics from MongoDB. The configuration generated by exporter worked for v4.2 and v4.4 of MongoDB, but failed for v5.0.
This change modifies configuration to work for v4.2, v4.4 and v5.0.
Fixes #432
> exporter: fix collstats compatibility issue

- .github/workflows/go.yml
Test matrix should test exporter against all versions of MongoDB which are officially supported. Hence MongoDB 5.0 is added. MongoDB 3.6 versions are removed, since they have hit EOL.
> Update test matrix for CI pipeline

- .golangci.yml
- Makefile
This change fixes following warnings noticed in CI pipeline:
**Diff stage**
```
bin/gofumpt -l -w -s ./main.go ./.github/check-license.go ./exporter/topology_info.go ./exporter/general_collector_test.go ./exporter/general_collector.go ./exporter/metrics.go ./exporter/topology_info_test.go ./exporter/collstats_collector.go ./exporter/serverstatus_collector.go ./exporter/diagnostic_data_collector_test.go ./exporter/base_collector.go ./exporter/collstats_collector_test.go ./exporter/dbstats_collector_test.go ./exporter/diagnostic_data_collector.go ./exporter/utils_test.go ./exporter/top_collector_test.go ./exporter/dbstats_collector.go ./exporter/common_test.go ./exporter/v1_compatibility.go ./exporter/debug_test.go ./exporter/v1_compatibility_test.go ./exporter/replset_status_collector.go …
```
> Fix CI pipeline warnings

- exporter/base_collector.go
- exporter/collstats_collector.go
- exporter/dbstats_collector.go
- exporter/diagnostic_data_collector.go
- exporter/diagnostic_data_collector_test.go
- exporter/exporter.go
- exporter/general_collector.go
- exporter/indexstats_collector.go
- exporter/replset_status_collector.go
- exporter/serverstatus_collector.go
- exporter/top_collector.go
- exporter/topology_info.go
- exporter/topology_info_test.go
Changed the way we instantiate the topology info object.
Now we call the newTopologyInfo and it never returns an error and the object is never nil. If it is not possible to connect, topology labels remain empty but we return a valid and not nill object.
Also added context termination check to avoid the ugly stack traces produced by context timeouts.
[PMM-9757](https://jira.percona.com/browse/PMM-9757) MongoDB exporter panics when DB connection is lost
[Feature build](https://github.com/Percona-Lab/pmm-submodules/pull/2403)
> PMM-9757 Fixed panic on lost connection

- exporter/base_collector.go
- exporter/collstats_collector.go
- exporter/dbstats_collector.go
- exporter/diagnostic_data_collector.go
- exporter/diagnostic_data_collector_test.go
- exporter/exporter.go
- exporter/general_collector.go
- exporter/indexstats_collector.go
- exporter/replset_status_collector.go
- exporter/serverstatus_collector.go
- exporter/top_collector.go
- exporter/topology_info.go
- exporter/topology_info_test.go
Changed the way we instantiate the topology info object.
Now we call the newTopologyInfo and it never returns an error and the object is never nil. If it is not possible to connect, topology labels remain empty but we return a valid and not nill object.
Also added context termination check to avoid the ugly stack traces produced by context timeouts.
[PMM-9757](https://jira.percona.com/browse/PMM-9757) MongoDB exporter panics when DB connection is lost
> Pmm 9757 panic on lost connection

- README.md
Apparently `enable.top` was renamed to `collector.topmetrics`. This updates the README to reflect that change.
> Update readme regarding `enable.top`

- .scripts/postinst
This PR should fix #480. Generally, it's good practice that options should use the full-name format for readability.
Added `--system` option, because it covers nologin shell option + good practice again, non-interactive users for software running on the server should be system users.
---
> Fix ambiguous postinst option -s

- exporter/common.go
- exporter/v1_compatibility.go
- internal/tu/docker_inspect.go
Comment format has been updated after Go 1.18, which is reflected in tip version of Golang. This patch updates comments to be compliant with new format.
> Update comments for gotip

- exporter/general_collector.go
- exporter/general_collector_test.go
- exporter/indexstats_collector_test.go
- exporter/replset_status_collector_test.go
Fix for [PMM-10271](https://jira.percona.com/browse/PMM-10271) and [PMM-10279](https://jira.percona.com/browse/PMM-10279)
Meta-metric generated for general collector were incorrectly labeled as dbstats. When dbstats and general collector were executed for a scrape request, two metric were generated with the same name and labels. This duplicate metric would trigger a panic in the metric generation library. This change updates the label for general collector and fixes the issue.
FB link : https://github.com/Percona-Lab/pmm-submodules/pull/2627
> PMM-10271 Fix meta-metric label for general collector

- exporter/exporter_test.go
This facilitates running tests locally as described in the [contributing guide](https://github.com/percona/mongodb_exporter/blob/main/CONTRIBUTING.md#running-tests) via `make test`.
When run outside of the docker network it is not possible to connect to each replica set member so this instructs the driver to connect only to the host provided.
[PMM-10693](https://jira.percona.com/browse/PMM-10693)
---
> Use direct connection for tests connecting to rs1

- exporter/diagnostic_data_collector_test.go
- exporter/v1_compatibility.go
[PMM-11137](https://jira.percona.com/browse/PMM-11137)
Build: [SUBMODULES-2945](https://github.com/Percona-Lab/pmm-submodules/pull/2945)
Updated existing metric to `mongodb_version_info{edition="Community",mongodb="4.2.23",vendor="MongoDB"}` from `mongodb_version_info{edition="Community",mongodb="server version is unavailable",vendor="MongoDB"}`
Test 1 for **mongos** in docker-compose.yml
```bash
./mongodb_exporter --mongodb.uri=mongodb://localhost:17000 --collector.replicasetstatus=true --log.level=debug --collect-all --web.listen-address=:9219 --compatible-mode=true
```
```bash
browse http://localhost:9219/metrics
```
```text
mongodb_version_info{edition="Community",mongodb="4.2.23",vendor="MongoDB"} 1
```
Test 2 for **mongo-1-1** in docker-compose.yml
```bash
./mongodb_exporter …
```
> PMM-11137 fetch version from buildInfo

- exporter/diagnostic_data_collector_test.go
- exporter/v1_compatibility.go
Do not create a metric mongodb_mongod_storage_engine if it's not possible to retrieve
For example, we can't get the type of engine for mongos instance. So in this case we can skip creating this metric.
[PMM-11247](https://jira.percona.com/browse/PMM-11247) (optional, if ticket reported)
- https://github.com/Percona-Lab/pmm-submodules/pull/2992
---
> PMM-11247: Do not create a metric mongodb_mongod_storage_engine if it's not possible to retrieve

- .goreleaser.yml
It is very important (from the legal point of view) to distribute the license together with binaries.
> add license files to packages

- REFERENCE.md
- exporter/currentop_collector.go
- exporter/currentop_collector_test.go
- exporter/exporter.go
- main.go
This is the implementation of the collector for notifications about too long requests are in processed.
For example:
```
apiVersion: v1
data:
kube-state-metrics-mongodb.rules: |-
groups:
- name: kube-state-metrics-mongodb.rules
rules:
- alert: MongodbCurrentQueryTime
expr: (mongodb_currentop_query_uptime > 3e+8) / 1000
labels:
severity: critical
annotations:
description: "Opid: {{ $labels.opid }}\nDesc: {{ $labels.desc }}\nNs: {{ $labels.ns }}\nOp : {{ $labels.op }}\nUptime : {{ $value }} ms\n"
summary: "MongoDB\nCurrent slow query on: {{ $labels.endpoint }}"
kind: ConfigMap
metadata:
labels:
app: prometheus
prometheus: kube-prometheus
release: kube-prometheus-stack
role: alert-rules
name: kube-prometheus-exporter-mongodb
namespace: monitoring
```
---
> Export currentOP uptime query metrics

- README.md
- REFERENCE.md
- exporter/exporter.go
- exporter/profile_status_collector.go
- exporter/profile_status_collector_test.go
- main.go
This implementation allows you to get metrics on slow queries.
```
mongodb_profile_slow_query_count{cl_id="58ffb6f25ee88911bb439499",cl_role="",database="admin",rs_state="2"} 1
mongodb_profile_slow_query_count{cl_id="58ffb6f25ee88911bb439499",cl_role="",database="config",rs_state="2"} 3
mongodb_profile_slow_query_count{cl_id="58ffb6f25ee88911bb439499",cl_role="",database="local",rs_state="2"} 0
```
--collector.profile-time-ts=30 Set time for scrape slow queries. This interval must be synchronized with the Prometheus scrape interval
For the collector to work, you must enable the profiler
https://www.mongodb.com/docs/manual/tutorial/manage-the-database-profiler/
This PR implements the functionality from this issue https://github.com/percona/mongodb_exporter/issues/707
---
> Collector for working with data from the system profile

- exporter/metrics.go
- exporter/metrics_test.go
This is useful for exporting oplog metrics in order to calculate the oplog window as the difference between `mongodb_ss_oplog_latestOptime` and `mongodb_ss_oplog_earliestOptime`
[PMM-6927](https://jira.percona.com/browse/PMM-6927)
---
> Add support for timestamp metrics with seconds precision

- .github/workflows/go.yml
- .github/workflows/release.yml
- exporter/currentop_collector_test.go
**Why**
As per the [Percona Software Support Lifecycle Policy](https://www.percona.com/services/policies/percona-software-support-lifecycle#mongodb) we can stop testing MongoDB version 4.2, which went End of Life.
> PMM-7 remove tests for mongodb v4.2

- Makefile
- docker-compose.yml
- docker/scripts/init-shard.sh
- docker/scripts/setup.sh
- exporter/diagnostic_data_collector.go
- exporter/diagnostic_data_collector_test.go
- exporter/exporter.go
- exporter/replset_status_collector_test.go
- exporter/shards_collector.go
- exporter/shards_collector_test.go
- exporter/topology_info.go
- exporter/topology_info_test.go
- exporter/v1_compatibility.go
- exporter/v1_compatibility_test.go
- internal/proto/replstatus.go
- internal/tu/testutils.go
- internal/util/util.go
- main.go
[PMM-12510](https://jira.percona.com/browse/PMM-12510)
[PMM-12510]: https://perconadev.atlassian.net/browse/PMM-12510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PMM-12510 correctly recognize arbiter nodes

- exporter/collstats_collector.go
- exporter/common.go
- exporter/common_test.go
- exporter/indexstats_collector.go
[PMM-12805](https://jira.percona.com/browse/PMM-12805)
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3534
[PMM-12805]: https://perconadev.atlassian.net/browse/PMM-12805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PMM-12805 Collstats, indexstats iterate only over collections, not views.

- main.go
- main_test.go
In issue https://github.com/percona/mongodb_exporter/issues/763 a user faced an error when connecting to the uri.
There is a bug when the mongodb user is prefixed with 'mongodb' that prevents the program to add the `mongodb://` uri prefix.
> Fix case where users are prefixed with mongodb

- exporter/currentop_collector.go
- exporter/currentop_collector_test.go
- exporter/exporter.go
- main.go
Issues: [#746](https://github.com/percona/mongodb_exporter/issues/746)
This bug fix limits the value of the metric received from CurrentOP() to the specified value.
This should relieve the Prometheus database of junk values.
> Reconsider inclusion of opid in mongodb_currentop_query_uptime

- exporter/common.go
Resolves #476 
As mentioned in the above issue, auto-discovery fails with a not authorized error when listing collections and using the clusterMonitor role.
> List only authorized collections

- README.md
As #809 stated, a `docker run` example in README expose port 17001, which is needless and mislead people. This PR remove that.
> Remove needless docker port expose of 17001 in README

- exporter/currentop_collector.go
- exporter/currentop_collector_test.go
[PMM-12848](https://jira.percona.com/browse/PMM-12848) (optional, if ticket reported)
--- …
> PMM-12848 Refactoring currentop_collector.

- main.go
PR #356 introduced an API option to disable default exporter metrics (process_* and go_*). However there is no command line flag to actually set this option. This change adds the command line flag `--no-collector.exporter-metrics` to disable those metrics.
> Add command line flag to disable metrics about the exporter it-self

- exporter/collstats_collector.go
See https://github.com/percona/mongodb_exporter/pull/893 When the database profiler is enabled a `system.profile` collection is created for which the collection of collstats is not possible. This results in `Unauthorized` errors.
For example:
```Sep 23 11:39:03 db-01 mongodb_exporter[53912]: time="2024-09-23T11:39:03Z" level=error msg="cannot get $collstats cursor for collection <database>.system.profile: (Unauthorized) not authorized on <database> to execute command { aggregate: \"system.profile\", pipeline: [ { $collStats: { latencyStats: { histograms: false }, storageStats: { scale: 1 } } }, { $project: { storageStats.wiredTiger: 0, storageStats.indexDetails: 0 } } ], cursor: {}, lsid: { id: UUID("<lsid>" }, $clusterTime: { clusterTime: Timestamp(<timestamp>, 1099), signature: { hash: …
```
> Remove system colections from collstats

- exporter/diagnostic_data_collector.go
- main.go
- main_test.go
[PMM-13477](https://jira.percona.com/browse/PMM-13477) Support of PSMDB 8.0.
[PMM-13543](https://jira.percona.com/browse/PMM-13543) Support socket path.
- https://github.com/percona/pmm/pull/3308
---
Once all checks pass and the code is ready for review, please add `pmm-review-exporters` team as the reviewer. That would …
> PMM-13543 Support socket path.

- exporter/server.go
- main.go
- main_test.go
[PMM-13543](https://jira.percona.com/browse/PMM-13543) (optional, if ticket reported)
--- …
> PMM-13543 Fix socket path failure.

- .golangci.yml
- exporter/collstats_collector.go
- exporter/collstats_collector_test.go
- exporter/diagnostic_data_collector.go
- exporter/exporter.go
- exporter/metrics.go
- exporter/metrics_test.go
- exporter/top_collector.go
- exporter/v1_compatibility.go
[PMM-13602](https://jira.percona.com/browse/PMM-13602) (optional, if ticket reported)
--- …
> PMM-13602 Improve performance

- exporter/diagnostic_data_collector_test.go
- exporter/v1_compatibility.go
Looks like they're mixed up.
Fixed mess with oldName and newName for mongodb_ss_wt_cache_maximum_bytes_configured
> mongodb_mongod_wiredtiger_cache_max_bytes -> mongodb_ss_wt_cache_maximum_bytes_configured (oldName and newName)

- exporter/multi_target_test.go
The multi-instance tests connects to multiple mongo instances in our test setup; one of them requires credentials but the test doesn't pass in any. This results in the following error:
```
time="2025-02-11T10:58:15+01:00" level=warning msg="cannot load topology labels: error getting cluster ID: (Unauthorized) command replSetGetConfig requires authentication: cannot get topology labels"
```
> PMM-7: use credentials for authenticated mongo instance

- README.md
> document required permissions for PBM collector

- .scripts/postinst
Setting up mongodb_exporter (0.43.1) ...
Creating user and group...
**invalid characters in Mongodb Exporter User at /usr/share/perl5/Debian/AdduserCommon.pm line 141. dpkg: error processing** package mongodb_exporter (--configure):
installed mongodb_exporter package post-installation script subprocess returned error exit status 255
> fix dpkg postinst adduser error in Debian 12.10

- .github/workflows/go.yml
This drops PSMDB/Mongo 4.4 images from our CI workflows since they've both been EOL for over a year and no longer supported.
> PMM-7: drop mongo 4.4 from CI

- .github/workflows/go.yml
- .goreleaser.yml
- Makefile
[PMM-13748](https://jira.percona.com/browse/PMM-13748)
[PMM-13959](https://jira.percona.com/browse/PMM-13959)
[PMM-13748]: https://perconadev.atlassian.net/browse/PMM-13748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PMM-13959]: https://perconadev.atlassian.net/browse/PMM-13959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PMM-13959 remove GSSAPI from main builds

- exporter/metrics.go
After profiling the exporter because it had a somewhat high cpu usage, it reported that the regexp operations in this function accounts for more than 10% of the cpu time. 
More precisely, the first call to prometheusize uses 3.79%, the second 5.86% (in exporter.MakeMetrics) and lastly it 1.03% (in exporter.MakeRawMetrics)
This all goes to zero if we cache them.
> Cache prometheusize rename between scrapes

- exporter/exporter.go
[PMM-14141](https://jira.percona.com/browse/PMM-14141) 
[PMM-14141]: https://perconadev.atlassian.net/browse/PMM-14141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PMM-14141: Respect Prometheus scrape-timeout header

- Makefile
[PMM-13748](https://jira.percona.com/browse/PMM-13748) 
[PMM-13748]: https://perconadev.atlassian.net/browse/PMM-13748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- https://github.com/percona/pmm/pull/4193
> PMM-13748: Add make command for building GSSAPI binaries

- exporter/common.go
The filter excluding view collections erronously also dropped collections with type "timeseries". This caused metrics from timeseries collections to not be collected (including basic ones, like mongotop and index accesses).
> Fix timeseries collections being ignored in discovery mode
